name: Deplyo Extension
on:
  push:
    branches:
        - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v
    - run: npm install
    - uses: lannonbr/vsce-action@master
        with:
            args: "publish -p $VSCE_TOKEN"
        env:
            VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
