name: Deplyo Extension
on:
  push:
    branches:
        - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v
    - name: GitHub Action for vsce
      uses: lannonbr/vsce-action@2.0.0

