name: Deplyo Extension
on:
  push:
    branches:
        - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - run: npm install
    - name: GitHub Action for vsce
      uses: lannonbr/vsce-action@2.0.0
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}


